# OpenClaw WeCom Relay Service - HTTP only (for certbot)
server {
    listen 80;
    server_name openclaw.qghub.cn;
    client_max_body_size 10m;

    location / {
        proxy_pass http://localhost:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-Ip $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 600s;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# 稍后生成ssl证书 sudo certbot --nginx -d openclaw.qghub.cn --non-interactive --agree-tos -m admin@qghub.cn